# Generated by Django 5.0.4 on 2024-07-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinventory',
            options={'verbose_name_plural': 'Book Inventory'},
        ),
    ]
