# Generated by Django 5.1.5 on 2025-02-23 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_book_cover'),
        ('store', '0002_alter_bookinventory_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='books.book')),
            ],
            options={
                'indexes': [models.Index(fields=['book', 'valid_from', 'valid_until'], name='store_bookp_book_id_dc628a_idx')],
            },
        ),
    ]
